name: Update README with Commit Count

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios

      - name: Fetch commit count
        id: commits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node fetch_commit_counts.js > commit_count.txt
          commit_count=$(cat commit_count.txt)
          echo "commit_count=$commit_count" >> $GITHUB_ENV

      - name: Update README
        run: |
          sed -i "s/<!-- COMMIT COUNT -->/$commit_count/" README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m "Update commit count"
          git push
